### ISSUE TITLE
[Android] Having trouble initializing the android plugin

### ISSUE THREAD

**Issue by zhouxhu** [sefidgaran/salesforce-marketing-cloud#11]
I found that android failed to initialize when using a plugin, and I suspect that I did not use MainApplication. However, there is no problem when using an example directly. What should I pay attention to when using plugins? thanks.

**Comment by zhouxhu** [comment]
Manifest merger failed : Attribute application@name value=(android.app.Application) from (unknown)
  	is also present at [:sfmc_plugin] AndroidManifest.xml:9:18-72 value=(com.example.sfmc_plugin.MainApplication).
  	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:3:4-33:19 to override.

**Comment by D41111410** [comment]
> I found that android failed to initialize when using a plugin, and I suspect that I did not use MainApplication. However, there is no problem when using an example directly. What should I pay attention to when using plugins? thanks.

Hi, did you figure this out? I'm having issues initializing in Android as well. iOS is working as expected
