### ISSUE TITLE
Salesforce with FCM

### ISSUE THREAD

**Issue by rodrigobastosv** [sefidgaran/salesforce-marketing-cloud#12]
I have a general question about the use of this plugin.

I found no way to set the user FCM Token to the salesforce. Is this not needed it all? It will just work without this step?

Sorry for the ignorance, but i am not very used with salesforce.

**Comment by alextarragosalle** [comment]
The plugin handles the retrieval of the token and the registration of the device. You only need to add the contactKey to the device you are registering and you should be able to find the linked Contact <> Device in your MC dashboard.

**Comment by rodrigobastosv** [comment]
Thanks very much!
