### ISSUE TITLE
Get contact key returns null on testflight

### ISSUE THREAD

**Issue by dtapat007** [sefidgaran/salesforce-marketing-cloud#13]
await SfmcPlugin().getContactKey() always returns null on app uploaded to testflight but works on debug. Any ideas why this is happening?

**Comment by sefidgaran** [comment]
Hello

Please provide more information, 
I guess if contactKey is null, it might be because of marketing cloud setting for production environment, looks like your device is not registered in MC.
please double check your MC settings and the app settings should be match.
