### ISSUE TITLE
setHandler method does not work for Android 

### ISSUE THREAD

**Issue by nvl-santamaria** [sefidgaran/salesforce-marketing-cloud#17]
I see you've added a comment in the code:-

"  /// (Applicable to iOS only - pass URL to Flutter through 'handle_url' methodCall.method - refer to example)"

How shall I make it work for Android as well ?

My requirement is to capture the url send from "Open Direct" and then navigate to that screen in the app.

**Comment by ifelsebreak** [comment]
For Android you can handle the url that gets passed with the notification directly in the AndroidManifest.xml, between the activity tags:

```
    <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data android:scheme="myscheme" android:host="myurl.com" />
                
    </intent-filter>
```

This will open the app when the user taps a notification that has the url **myscheme://myurl.com**

**Comment by nvl-santamaria** [comment]
Thanks allot @ifelsebreak 
That worked 👍
