### ISSUE TITLE
iOS app push notification link issue while app is closed

### ISSUE THREAD

**Issue by sefidgaran** [sefidgaran/salesforce-marketing-cloud#2]
Existed issue regarding iOS:

```
1. Given iOS app is not running (closed) 
2. When push notification received
3. And user tap on notification carring a link
4. sfmc_handle not called!
```

Pull requests OR solution to this issue are welcomed.
Thanks in advance

**Comment by sefidgaran** [comment]
Update: After investigating more and test the [official learning app from Salesforce 7.6](https://github.com/salesforce-marketingcloud/MarketingCloudSDK-iOS/tree/master/LearningApp
),
same issue observed, so this issue looks like a SFMC SDK issue.
Any updates are welcomed.
Thanks

**Comment by sefidgaran** [comment]
Update: After migrating Marketing Cloud SDK iOS to version 8.0.8 and SFMCSdk 1.0.6, I managed to fix this issue.
Now in iOS when app is killed, URL in push notification will be received.

So, issue resolved.

**Comment by ifelsebreak** [comment]
We are experiencing the same behaviour.
Even with the latest version of sfmc_plugin, the url handler isn't called when the app is in terminated state. 
Tapping the notification opens the app on the home page.

**Comment by SimonLauridsen** [comment]
I'm experiencing the same issue - and I'm running version 8.0.13. @sefidgaran Did you do something speciel to make it work? Or did it just work out of the box all of a sudden?

**Comment by lucasgarcez-bilue** [comment]
I'm facing the same issue with my React Native App. useng the [react-native-marketingcloudsdk](https://github.com/salesforce-marketingcloud/react-native-marketingcloudsdk) that wraps the iOS SDK. 
I have the `sfmc_handleURL` implemented on the `AppDelegate.mm,`, and it calls on a push notification is opened with the App in the background, but it doesn't happen if the App is closed. The notification takes the user to the Home Screen and doesn't call the `sfmc_handleURL.`

**Comment by fernandosev** [comment]
I was having the same problem.

Solved by adding the follow code after [self pushSetup];

```objective-c
if (launchOptions != nil && [launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey] != nil) {
      NSDictionary *userInfo = [launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey];
      [[SFMCSdk mp] setNotificationUserInfo:userInfo];
}
```

Now, OpenDirect, Opened tracking count and other functions work well.

**Comment by fernandosev** [comment]
Works fine after adding the follow code on AppDelegate.mm > -(BOOL)application.

Obs.: After MKC configuration

```ObjectiveC
if (newLaunchOptions != nil && [newLaunchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey] != nil) {
          NSDictionary *userInfo = [newLaunchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey];
          [[SFMCSdk mp] setNotificationUserInfo:userInfo];
        
        if (userInfo[@"_od"]) {
            NSString *initialURL = userInfo[@"_od"];
            if (!newLaunchOptions[UIApplicationLaunchOptionsURLKey]) {
              newLaunchOptions[UIApplicationLaunchOptionsURLKey] = [NSURL URLWithString:initialURL];
            }
        }
      }
```

**Comment by MichaelWheldon** [comment]
Confirmed the above is a must for cold starts. The SDK (at least on ios side) specifically will not handle these opens for you.

As an aside, I wish the default payload shape was listed somewhere in the documentation, would save devs a lot of effort.
